[workspace]
members = [
    "function-trigger-deployer-rs",
    "function-deployer-rs",
    "function-invoker-rs",
    "function-report-log-processor-rs",
    "common_lib"
]
resolver = "2"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'