[workspace]

members = [
    "function-trigger-deployer-rs",
    "function-deployer-rs",
    "function-snapstart-deployer-rs",
]

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'