ARG baseImage
FROM ${baseImage}
ARG handlerCode
ARG handlerCmd

COPY ./${handlerCode} /var/runtime
COPY ./${handlerCode} /var/task
RUN chmod +x /var/task/bootstrap || true
RUN chmod +x /var/runtime/bootstrap || true
ENV LAMBDA_PERF_CMD=${handlerCmd}
CMD [ ${LAMBDA_PERF_CMD} ]