ARG baseImage
FROM ${baseImage}
ARG handlerCode
ARG handlerCmd
COPY ./${handlerCode}/bootstrap* /var/runtime
COPY ./${handlerCode} /var/task
ENV LAMBDA_PERF_CMD=${handlerCmd}
CMD [ ${LAMBDA_PERF_CMD} ]