name: autobuild

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '50 8 * * *'
  workflow_dispatch:

jobs:
  trigger-push-to-s3-arm64:
    - uses: ./.github/workflows/push-to-s3.yml
      with:
        region: 'eu-west-1'
        architecture: 'arm64'