name: AWS publish artifacts to S3

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        type: choice
        options:
          - DEV
          - TEST
        required: true
      architecture:
        description: 'Architecture'
        type: choice
        options:
          - x86_64
          - arm64
        required: true

jobs:
  trigger-push-to-s3:
    uses: ./.github/workflows/push-to-s3.yml
    with:
      region: ${{ inputs.environment == 'DEV' && secrets.AWS_DEV_REGION || secrets.AWS_PROD_REGION }}
      architecture: ${{ inputs.architecture }}
    secrets:
      role: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      account_id: ${{ secrets.AWS_ACCOUNT_ID }}
