name: AWS publish artifacts to S3

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        type: choice
        options:
          - DEV
          - PROD
        required: true
      architecture:
        description: 'Architecture'
        type: choice
        options:
          - x86_64
          - arm64
        required: true

jobs:
  trigger-push-to-s3:
    runs-on: ubuntu-latest
    env:
      REGION: ${{ inputs.environment == 'PROD' && secrets.AWS_PROD_REGION || secrets.AWS_DEV_REGION }}
    steps:
      - name: Trigger Push to S3 Workflow
        uses: ./.github/workflows/push-to-s3.yml
        with:
          architecture: ${{ inputs.architecture }}
          region: ${{ env.REGION }}
        secrets:
          role: ${{ secrets.AWS_ROLE_TO_ASSUME }}