name: AWS publish artifacts to S3

permissions:
  id-token: write
  contents: read

on:
  workflow_run:
    workflows: ["autobuild"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      region:
        description: 'region on which you want to deploy'
        required: true
      architecture:
        description: 'architecture'
        required: true

jobs:
  setup:
    runs-on: ubuntu-24.04
    outputs:
      runner: ${{ steps.select.outputs.runner }}
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Check branch
        id: select
        run: |
          if [ ${{ inputs.architecture }} == 'x86_64' ]; then
            echo "runner=ubuntu-24.04" >> $GITHUB_OUTPUT
          else
            echo "runner=ubuntu-24.04-arm" >> $GITHUB_OUTPUT
          fi
          cat $GITHUB_OUTPUT
      - uses: actions/checkout@v4
      - name: Build runtime matrix
        id: set-matrix
        run: |
          jq -c '[.runtimes[] | select(.architectures | index("${{ inputs.architecture }}")) | .path]' manifest.json
          echo "matrix=$(jq -c '[.runtimes[] | select(.architectures | index("${{ inputs.architecture }}")) | .path]' manifest.json)" >> $GITHUB_OUTPUT

  build-upload:
    needs: setup
    runs-on: ${{ needs.setup.outputs.runner }}
    strategy:
      fail-fast: false
      matrix: 
        runtime_id: ${{fromJson(needs.setup.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHub_Action_LambdaPerf_Session
          aws-region: ${{ inputs.region }}
      - name: Delete huge unnecessary folders
        run: |
          rm -rf /opt/hostedtoolcache
          rm -rf /usr/share/dotnet
          rm -rf /opt/ghc
          rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: build and deploy
        env:
          ARCHITECTURE: ${{ inputs.architecture }}
          AWS_REGION: ${{ inputs.region }}
          RUNTIME_ID: ${{ matrix.runtime_id }}
        run: |
          cd s3-uploader
          yarn install
          node app.mjs