name: AWS publish artifacts to S3

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        type: choice
        options:
          - DEV
          - PROD
        required: true
      architecture:
        description: 'Architecture'
        type: choice
        options:
          - x86_64
          - arm64
        required: true

jobs:
  trigger-push-to-s3:
    uses: ./.github/workflows/push-to-s3.yml
    with:
      architecture: ${{ inputs.architecture }}
      environment: ${{ inputs.environment }}
    secrets:
      role: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      devRegion: ${{ secrets.AWS_DEV_REGION }}
      prodRegion: ${{ secrets.AWS_PROD_REGION }}