name: AWS publish artifacts to S3

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'region on which you want to deploy'
        type: choice
        options:
          - dev
          - prod
        required: true
      architecture:
        description: 'architecture'
        type: choice
        options:
          - x86_64
          - arm64
        required: true

jobs:
  trigger-push-to-s3:
    env:
      AWS_REGION: ${{ inputs.region == 'DEV' && secrets.DEV_REGION || inputs.region == 'PROD' && secrets.PROD_REGION }}
    uses: ./.github/workflows/push-to-s3.yml
    with:
      region: ${{ env.REGION }}
      architecture: ${{ inputs.architecture }}
    secrets:
      role: ${{ secrets.AWS_ROLE_TO_ASSUME }}
  