name: test build runtimes

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  trigger-push-to-s3:
    strategy:
      matrix:
        architecture: [x86_64, arm64]
    uses: ./.github/workflows/push-to-s3.yml
    with:
      region: 'us-east-1'
      architecture: ${{ matrix.architecture }}
    secrets:
      role: ${{ secrets.AWS_ROLE_TO_ASSUME }}