name: test build arm on macos-14

on:
  push:
    
jobs:
  test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - name: Install docker
        run: brew install docker --cask
      - name: Print docker version
        run: docker --version
      - name: Test context
        run: docker context use default
      - name: Install plugin buildx
        run: docker plugin install buildx
      - name: buildx
        run: docker buildx create --platform linux/arm64,linux/arm/v8 maxday_builder
      - name: test build arm
        run: cd s3-uploader/runtimes/rust_on_provided_al2023 && docker buildx build .




