name: test build arm on macos-14

on:
  push:
    
jobs:
  test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - name: Install docker
        run: brew install docker --cask
      - name: Print docker version
        run: docker --version
      - name: Create symlink
        run: ls -l /var/run/docker.sock
      - name: List context
        run: docker context ls
      # - name: test build arm
      #   run: cd s3-uploader/runtimes/rust_on_provided_al2023 && docker buildx build .




